import "./Features.css";
import search from "../../assets/images/search.png";
import select from "../../assets/images/select.png";
import standOut from "../../assets/images/standOut.png";


function FeatureSteps() {
  return (
    <div className="feature__container">
      <div className="feature__sub-container">
        <img src={search} alt="icon" />
        <p className="feature__name">Search</p>
        <p className="feature__text">
          Simply add a keyword or a term related to your business in the slogan
          maker search box. Wait for the magic to happen.
        </p>
      </div>
      <div className="feature__sub-container">
        <img src={select} alt="icon" />
        <p className="feature__name">Select</p>
        <p className="feature__text">
          Choose from thousands of options generated by the slogan maker that
          fit your needs.
        </p>
      </div>
      <div className="feature__sub-container">
        <div className="last__feature">
          <img src={standOut} alt="icon" />
        </div>
        <p className="feature__name">Stand out</p>
        <p className="feature__text">
          Congrats on your new slogan. It's time to win the world!
        </p>
      </div>
    </div>
  );
}

export { FeatureSteps };
